// Generated by https://quicktype.io

export interface FetchAllPokemonsResponse {
    count:    number;
    next:     null;
    previous: null;
    results:  SmallPokemons[];
}

export interface SmallPokemons {
    name: string;
    url:  string;
}

export interface Pokemons {
    id: string;
    name: string;
    picture:  string;
}


